### PR TITLE
fix: pretty url for pagination links

### PR DESCRIPTION
**Pull request by morvy**
Fixes ?paged=X on pagination links

### CODE REVIEW

**Comment by XjSv** [comment]
Looking good at first sight. Going to do a little testing to make sure nothing else breaks.

**Comment by XjSv** [comment]
It looks like it works as expected but I'm wondering if it could be done in a better way. For example this could work too and it seems simpler:

```php
$base_url = get_pagenum_link(1);
$recipe_pagination = apply_filters('cooked_pagination_args', [
  'base' => $base_url . '/page/%#%',
  'format' => '/page/%#%',
  'mid-size' => 1,
  'current' => $current_recipe_page,
  'total' => $total_recipe_pages,
  'prev_next' => true,
  'prev_text' => '<i class="cooked-icon cooked-icon-angle-left"></i>',
  'next_text' => '<i class="cooked-icon cooked-icon-angle-right"></i>'
]);
```

Since `get_pagenum_link(1)` will return the base URL such as "https://example.ddev.site/browse-recipes", then we can safely append `'/page/%#%'` to it.

**Comment by morvy** [comment]
Hi,

I've taken the $big integer from official docs and I've seen mostly everyone doing it this way. The reason to use a pagination link for an unlikely page is to get pagination_base in the url and then just replace the $big integer with placeholder.

**Comment by XjSv** [comment]
I understand your logic and I have seen some example online doing it that way, but from my testing,  `get_pagenum_link(1)` returns the base URL such as `https://www.example.com/browse-recipes` and NOT `https://www.example.com/browse-recipes/page/1` because `/browse-recipes` and `/browse-recipes/page/1` are the same thing and go to the same page.

In your example and the examples online it seems unnecessary to do `get_pagenum_link(999999999)` and then do a string replace to remove the '999999999' when you can get the original base URL simply by `get_pagenum_link(1)`.

```
get_pagenum_link(999999999) -> https://www.example.com/browse-recipes/page/999999999
get_pagenum_link(1) -> https://www.example.com/browse-recipes
```
So if you call `get_pagenum_link(1)` and then append `'/page/%#%'` that should do the trick.

The parameter 1 is also the default so its not strictly necessary. Calling `get_pagenum_link()` will do the same thing.

I also don't think the `esc_url()` is required since there is no user input here and the URL would be generated from `get_pagenum_link()`. Additionally the URL returned from `get_pagenum_link()` is escaped by default. See docs here: https://developer.wordpress.org/reference/functions/get_pagenum_link/

It's easier to understand the logic and there are 2 less function calls which makes the code more efficient.

**Comment by morvy** [comment]
You're right about escaping, that can save some processing, but the reason behind 99999999 is that it returns full url with [pagination base](https://github.com/WordPress/wordpress-develop/blob/6.5/src/wp-includes/link-template.php#L2444). Your code would hardcode "page" into the string, but I have a client who wants it translated (and his shop/blog urls are all translated) and I believe I'm not the only one.

**Comment by XjSv** [comment]
You bring up a good point, I did not consider that. In that case, can you remove the `esc_url()` since it's being done automatically and I can merge this in and get it ready for the next release.

**Review by XjSv — APPROVED** [review]

**Pull request merged**
